"""Full startup application records for seeding."""

MINIMAL_PDF = b"%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF"
MINIMAL_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06"
    b"\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00"
    b"\x01\r\n-\xdb\x00\x00\x00\x00IEND\xaeB`\x82"
)


def application_records(admin_id: int, user1_email: str) -> list[dict]:
    """Return application dicts; pitch_deck_path filled by seed script."""
    return [
        {
            "startup_name": "Apex AI Labs",
            "website_url": "https://apexailabs.example",
            "founder_names": "Alice Vance, Bob Carter",
            "contact_email": user1_email,
            "contact_number": "+91 98765 43210",
            "linkedin_founder": "https://linkedin.com/in/alicevance",
            "linkedin_company": "https://linkedin.com/company/apex-ai-labs",
            "linkedin_profile": "https://linkedin.com/in/alicevance | https://linkedin.com/company/apex-ai-labs",
            "hq_location": "Bangalore, India",
            "year_of_incorporation": 2023,
            "problem_statement": "Training large vision models costs millions and excludes most startups from cutting-edge AI.",
            "solution_overview": "Distributed GPU compute marketplace reducing training cost ~60% via spot orchestration.",
            "industry_sector": "AI / ML",
            "business_model": "SaaS",
            "current_stage": "MVP",
            "core_product_description": "API + dashboard for scheduling multi-node training jobs across providers.",
            "technology_stack": "Python, Kubernetes, PyTorch, Rust scheduler",
            "unique_value_proposition": "10x cheaper burst training vs single-cloud reserved GPUs",
            "ip_patents": "Provisional filed 2024",
            "demo_link": "https://demo.apexailabs.example",
            "target_market": "TAM USD 45B MLOps infra; SAM USD 4B startup/enterprise ML teams; SOM USD 200M APAC",
            "customer_segment": "AI-first startups and enterprise ML platform teams",
            "key_competitors": "Lambda Labs, CoreWeave, AWS SageMaker",
            "competitive_advantage": "Multi-cloud arbitrage + automatic checkpoint recovery",
            "current_revenue": "$8,000 MRR (~$96K ARR)",
            "growth_rate": "12% MoM",
            "number_of_customers": "24 paying teams",
            "key_partnerships": "NVIDIA Inception, AWS Activate",
            "notable_achievements": "TechCrunch Startup Battlefield finalist 2024",
            "funding_raised_till_date": "$150,000 pre-seed",
            "investors": "Angel syndicate (2 angels)",
            "burn_rate": "$42,000/month",
            "runway_months": 8,
            "revenue_projections": "Y1: $250K ARR | Y2: $1.1M ARR | Y3: $3.8M ARR",
            "amount_raising": "$500,000 USD",
            "funding_stage": "Seed",
            "equity_offered": "10%",
            "use_of_funds": "40% engineering, 25% GTM, 20% cloud credits, 10% ops/legal, 5% reserve",
            "founder_background": "Alice: ex-Google Brain. Bob: ex-AWS EC2 networking.",
            "core_team_members": "6 FTE — 4 engineers, 1 sales, 1 ops",
            "advisors_mentors": "Prof. Rajan (IISc), former VP Eng at Freshworks",
            "why_partner": "FSV's AI thesis and enterprise intro network in India.",
            "how_add_value": "Bank pilot intros and hiring support.",
            "open_to_mentorship": "Yes",
            "financial_model_path": "docs/financial-model/samples/Apex_AI_Labs_Financial_Model.xlsx",
            "company_registered": "Yes",
            "legal_issues": "No",
            "consent_given": "Yes",
            "deal_score": 85.5,
            "status": "Submitted",
        },
        {
            "startup_name": "Quantum Security",
            "website_url": "https://quantumsec.io",
            "founder_names": "Dr. Sarah Chen",
            "contact_email": "founder@quantumsec.io",
            "contact_number": "+1 415 555 2671",
            "linkedin_founder": "https://linkedin.com/in/sarahchen-quantum",
            "linkedin_company": "https://linkedin.com/company/quantum-security",
            "linkedin_profile": "https://linkedin.com/in/sarahchen-quantum",
            "hq_location": "San Francisco, USA",
            "year_of_incorporation": 2021,
            "problem_statement": "Enterprises must migrate to post-quantum cryptography before harvest-now-decrypt-later attacks.",
            "solution_overview": "One-click quantum-safe VPN and key-exchange APIs for developers.",
            "industry_sector": "Blockchain",
            "business_model": "B2B SaaS",
            "current_stage": "Growth Stage",
            "core_product_description": "PQC TLS termination + SDK for mobile and server apps.",
            "technology_stack": "C++, Rust, NIST PQC algorithms",
            "unique_value_proposition": "Fastest enterprise rollout vs manual OpenSSL migrations",
            "ip_patents": "2 granted US patents",
            "demo_link": "https://docs.quantumsec.io/demo",
            "target_market": "TAM USD 12B cybersecurity; SAM USD 1.2B enterprise PQC",
            "customer_segment": "Fortune 500 security teams, regulated banks",
            "key_competitors": "ISARA, PQShield, Cloudflare PQC beta",
            "competitive_advantage": "Patented hybrid handshake; FIPS path in progress",
            "current_revenue": "$180,000 MRR",
            "growth_rate": "8% MoM",
            "number_of_customers": "14 enterprise logos",
            "key_partnerships": "Deloitte cyber alliance",
            "notable_achievements": "SOC2 Type II certified",
            "funding_raised_till_date": "$3.2M seed",
            "investors": "CyberVentures, university grant",
            "burn_rate": "$220,000/month",
            "runway_months": 14,
            "revenue_projections": "Y1: $3M ARR | Y2: $8M ARR | Y3: $18M ARR",
            "amount_raising": "$2,000,000 USD",
            "funding_stage": "Series A",
            "equity_offered": "15%",
            "use_of_funds": "US enterprise sales, FIPS certification, R&D",
            "founder_background": "PhD MIT cryptography; ex-Cloudflare research",
            "core_team_members": "22 FTE",
            "advisors_mentors": "Former CISO major US bank",
            "why_partner": "FSV DeepTech + blockchain network.",
            "how_add_value": "APAC bank introductions.",
            "open_to_mentorship": "Yes",
            "financial_model_path": "docs/financial-model/FSV_Financial_Model_Template.xlsx",
            "company_registered": "Yes",
            "legal_issues": "No",
            "consent_given": "Yes",
            "deal_score": 92.0,
            "status": "Accepted",
            "reviewer_id": admin_id,
            "reviewer_notes": "Highly experienced academic founder. Exceptional technical depth.",
        },
        {
            "startup_name": "PayGrid India",
            "website_url": "https://paygrid.in",
            "founder_names": "Rohan Mehta, Priya Nair",
            "contact_email": "founders@paygrid.in",
            "contact_number": "+91 99887 76655",
            "hq_location": "Mumbai, India",
            "year_of_incorporation": 2022,
            "problem_statement": "Indian SMBs wait 45+ days for B2B invoice payments, hurting working capital and supplier trust.",
            "solution_overview": "UPI-native invoice financing embedded in Tally and Zoho Books with automated underwriting.",
            "industry_sector": "Fintech",
            "business_model": "B2B",
            "current_stage": "Early Revenue",
            "target_market": "TAM USD 8B India SMB credit; SAM USD 800M invoice financing",
            "current_revenue": "$22,000 MRR",
            "growth_rate": "18% MoM",
            "number_of_customers": "340 SMB merchants",
            "amount_raising": "$1,200,000 USD",
            "funding_stage": "Seed",
            "equity_offered": "12%",
            "use_of_funds": "Lending capital facility, engineering, compliance",
            "company_registered": "Yes",
            "legal_issues": "No",
            "consent_given": "Yes",
            "deal_score": 81.0,
            "status": "Under Review",
            "reviewer_id": admin_id,
            "reviewer_notes": "Strong UPI tailwinds; monitor NBFC partnership risk.",
        },
        {
            "startup_name": "EcoHarvest Tech",
            "founder_names": "Marcus Thorne",
            "contact_email": "marcus@ecoharvest.com",
            "contact_number": "+61 2 9876 5432",
            "hq_location": "Sydney, Australia",
            "year_of_incorporation": 2022,
            "problem_statement": "Farm waste methane emissions and lost revenue for growers.",
            "solution_overview": "IoT bio-digesters turning waste into power; carbon credit marketplace.",
            "industry_sector": "DeepTech",
            "business_model": "Marketplace",
            "current_stage": "Early Revenue",
            "current_revenue": "$15,000 MRR",
            "growth_rate": "6% MoM",
            "number_of_customers": "12 farm deployments",
            "amount_raising": "$1,000,000 USD",
            "funding_stage": "Seed",
            "use_of_funds": "Manufacturing APAC pilots",
            "company_registered": "Yes",
            "legal_issues": "No",
            "consent_given": "Yes",
            "deal_score": 78.4,
            "status": "Under Review",
            "reviewer_id": admin_id,
            "reviewer_notes": "Hardware execution risk; interesting carbon angle.",
        },
        {
            "startup_name": "BioPulse Systems",
            "founder_names": "Emma Watson, Dev Patel",
            "contact_email": "contact@biopulse.com",
            "contact_number": "+44 20 7946 0192",
            "hq_location": "London, UK",
            "year_of_incorporation": 2024,
            "problem_statement": "Invasive glucose monitoring limits diabetic patient adherence.",
            "solution_overview": "Optical non-invasive glucose sensing in wearable form factor.",
            "industry_sector": "HealthTech",
            "business_model": "B2C",
            "current_stage": "Idea",
            "current_revenue": "Pre-revenue — 200 waitlist signups",
            "growth_rate": "N/A",
            "number_of_customers": "0 paying",
            "amount_raising": "$250,000 USD",
            "funding_stage": "Pre-seed",
            "use_of_funds": "Prototype and clinical feasibility",
            "company_registered": "No",
            "legal_issues": "No",
            "consent_given": "Yes",
            "deal_score": 45.0,
            "status": "Rejected",
            "reviewer_id": admin_id,
            "reviewer_notes": "Too early; regulated health path.",
        },
        {
            "startup_name": "ChainLedger",
            "website_url": "https://chainledger.dev",
            "founder_names": "Vikram Singh",
            "contact_email": "vikram@chainledger.dev",
            "contact_number": "+65 9123 4567",
            "hq_location": "Singapore",
            "year_of_incorporation": 2023,
            "problem_statement": "Cross-border B2B settlements take 3–5 days with opaque fees.",
            "solution_overview": "Permissioned stablecoin rails for ASEAN exporter/importer net settlement.",
            "industry_sector": "Blockchain",
            "business_model": "B2B SaaS",
            "current_stage": "MVP",
            "current_revenue": "$4,500 MRR pilot revenue",
            "growth_rate": "22% MoM",
            "number_of_customers": "8 pilot corporates",
            "amount_raising": "$750,000 USD",
            "funding_stage": "Seed",
            "use_of_funds": "Licences, engineering, compliance",
            "company_registered": "Yes",
            "legal_issues": "No",
            "consent_given": "Yes",
            "deal_score": 72.0,
            "status": "Submitted",
        },
    ]
